export const MODELS = [
  {
    id: "veo-3.1",
    name: "Google Veo 3.1",
    description: "Cinematic motion with synchronized audio in native 1080p",
    tier: "free" as const,
    badge: "Starter",
    hasAudio: true,
    maxQuality: "1080p",
    durations: [5, 8, 10],
    aspectRatios: ["16:9", "9:16", "1:1"],
    creditCost: { 5: 1, 8: 2, 10: 3 } as Record<number, number>,
  },
  {
    id: "kling-2.1",
    name: "Kling 2.1",
    description: "Versatile generation with consistent motion and strong prompt following",
    tier: "basic" as const,
    badge: null,
    hasAudio: false,
    maxQuality: "1080p",
    durations: [5, 10],
    aspectRatios: ["16:9", "9:16", "1:1"],
    creditCost: { 5: 2, 10: 3 } as Record<number, number>,
  },
  {
    id: "kling-2.5-turbo",
    name: "Kling 2.5 Turbo",
    description: "Fast turbo generation with negative prompt support",
    tier: "basic" as const,
    badge: null,
    hasAudio: false,
    maxQuality: "720p",
    durations: [5],
    aspectRatios: ["16:9", "9:16", "1:1"],
    creditCost: { 5: 2 } as Record<number, number>,
  },
  {
    id: "hailuo-2.3",
    name: "Hailuo 2.3",
    description: "Expressive characters with realistic motion and cinematic quality",
    tier: "basic" as const,
    badge: null,
    hasAudio: false,
    maxQuality: "768p",
    durations: [6],
    aspectRatios: ["16:9", "9:16", "1:1"],
    creditCost: { 6: 2 } as Record<number, number>,
  },
  {
    id: "wan-2.6",
    name: "Wan 2.6",
    description: "Affordable 1080p with stable character consistency and audio",
    tier: "basic" as const,
    badge: null,
    hasAudio: true,
    maxQuality: "1080p",
    durations: [5],
    aspectRatios: ["16:9", "9:16", "1:1"],
    creditCost: { 5: 2 } as Record<number, number>,
  },
  {
    id: "bytedance-seedance",
    name: "Bytedance Seedance",
    description: "Fast generation with multi-shot scene cuts and camera control",
    tier: "basic" as const,
    badge: null,
    hasAudio: false,
    maxQuality: "720p",
    durations: [5],
    aspectRatios: ["16:9", "9:16", "1:1"],
    creditCost: { 5: 2 } as Record<number, number>,
  },
  {
    id: "kling-3.0",
    name: "Kling 3.0",
    description: "Multi-shot storytelling with native sound effects up to 15s",
    tier: "pro" as const,
    badge: "Premium",
    hasAudio: true,
    maxQuality: "pro",
    durations: [5, 10, 15],
    aspectRatios: ["16:9", "9:16", "1:1"],
    creditCost: { 5: 3, 10: 5, 15: 8 } as Record<number, number>,
  },
  {
    id: "grok-imagine",
    name: "Grok Imagine",
    description: "xAI model with coherent motion and synchronized audio output",
    tier: "pro" as const,
    badge: "Premium",
    hasAudio: true,
    maxQuality: "480p",
    durations: [6, 10],
    aspectRatios: ["16:9", "9:16", "1:1", "2:3"],
    creditCost: { 6: 3, 10: 5 } as Record<number, number>,
  },
  {
    id: "runway-gen4-turbo",
    name: "Runway Gen-4 Turbo",
    description: "Cinematic quality with fast turnaround and multiple aspect ratios",
    tier: "pro" as const,
    badge: "Popular",
    hasAudio: false,
    maxQuality: "1080p",
    durations: [5, 10],
    aspectRatios: ["16:9", "9:16", "1:1", "4:3"],
    creditCost: { 5: 2, 10: 4 } as Record<number, number>,
  },
  {
    id: "runway-aleph",
    name: "Runway Aleph",
    description: "In-context editing — change objects, lighting, angles, or styles via prompts",
    tier: "pro" as const,
    badge: "Premium",
    hasAudio: false,
    maxQuality: "1080p",
    durations: [5, 10],
    aspectRatios: ["16:9", "9:16", "1:1", "4:3", "3:4"],
    creditCost: { 5: 3, 10: 5 } as Record<number, number>,
  },
  {
    id: "sora-2",
    name: "Sora 2",
    description: "OpenAI's premium model with audio and durations up to 20s",
    tier: "pro" as const,
    badge: "Premium",
    hasAudio: true,
    maxQuality: "1080p",
    durations: [5, 10, 15, 20],
    aspectRatios: ["16:9", "9:16", "1:1"],
    creditCost: { 5: 3, 10: 5, 15: 7, 20: 10 } as Record<number, number>,
  },
] as const;

export type ModelId = (typeof MODELS)[number]["id"];
export type Tier = "free" | "basic" | "pro" | "enterprise";

export const MODEL_CATEGORIES = [
  {
    id: "cinematic",
    name: "Cinematic",
    icon: "Clapperboard" as const,
    description: "Film-quality, dramatic motion",
    basicModelId: "kling-2.1",
    premiumModelId: "runway-gen4-turbo",
  },
  {
    id: "social-media",
    name: "Social Media",
    icon: "Share2" as const,
    description: "Reels, TikToks, with synchronized audio",
    basicModelId: "wan-2.6",
    premiumModelId: "sora-2",
  },
  {
    id: "quick-easy",
    name: "Quick & Easy",
    icon: "Zap" as const,
    description: "Fast turnaround, budget-friendly",
    basicModelId: "kling-2.5-turbo",
    premiumModelId: "bytedance-seedance",
  },
  {
    id: "with-audio",
    name: "With Audio",
    icon: "Volume2" as const,
    description: "General sound & voiceover effects",
    basicModelId: "veo-3.1",
    premiumModelId: "kling-3.0",
  },
  {
    id: "creative-editing",
    name: "Creative / Editing",
    icon: "Palette" as const,
    description: "Artistic styles, video editing",
    basicModelId: "hailuo-2.3",
    premiumModelId: "runway-aleph",
  },
] as const;

export type CategoryId = (typeof MODEL_CATEGORIES)[number]["id"];

export const STYLES = [
  { id: "product-showcase", name: "Product Showcase", icon: "Package", description: "Clean rotation and highlighting" },
  { id: "ugc", name: "UGC", icon: "Smartphone", description: "User-generated content feel" },
  { id: "luxury", name: "Luxury", icon: "Diamond", description: "Premium, slow-motion elegance" },
  { id: "social-media-ad", name: "Social Media Ad", icon: "Megaphone", description: "Eye-catching, fast-paced" },
  { id: "lifestyle", name: "Lifestyle", icon: "Sun", description: "Natural, warm, authentic" },
  { id: "unboxing", name: "Unboxing", icon: "Gift", description: "Reveal and unbox animation" },
  { id: "custom", name: "Custom", icon: "Pencil", description: "Write your own prompt" },
] as const;

export type StyleId = (typeof STYLES)[number]["id"];

export const SUPPORTED_IMAGE_TYPES = [
  "image/jpeg",
  "image/png",
  "image/webp",
  "image/tiff",
  "image/bmp",
];

export const SUPPORTED_IMAGE_EXTENSIONS = [
  ".jpg", ".jpeg", ".png", ".webp", ".tiff", ".tif", ".bmp",
  ".cr2", ".nef", ".arw", ".dng", ".orf", ".rw2",
];

export const MAX_FILE_SIZE = 20 * 1024 * 1024; // 20MB

export const TIERS = [
  {
    id: "free" as const,
    name: "Free",
    price: 0,
    credits: 1,
    features: [
      "1 free video on signup",
      "All 11 AI models",
      "Standard quality",
    ],
  },
  {
    id: "basic" as const,
    name: "Basic",
    price: 10,
    credits: 10,
    features: [
      "10 credits/month",
      "All 11 AI models",
      "No watermark",
      "HD quality",
    ],
  },
  {
    id: "pro" as const,
    name: "Pro",
    price: 25,
    credits: 30,
    features: [
      "30 credits/month",
      "All 11 AI models",
      "No watermark",
      "Priority generation",
      "Model comparison",
    ],
  },
  {
    id: "enterprise" as const,
    name: "Enterprise",
    price: null,
    credits: null,
    features: [
      "Unlimited credits",
      "All 11 AI models",
      "No watermark",
      "Priority support",
      "API access",
      "Custom branding",
    ],
  },
];
