export const STYLE_PROMPTS: Record<string, string> = {
  "product-showcase":
    "CRITICAL CONSTRAINT: Preserve the subject's exact design, shape, color, logo, and surface textures — zero modifications allowed. Begin with a tight macro close-up of the subject resting on a seamless, softly reflective obsidian surface. The camera executes an ultra-smooth, continuous 360-degree orbital arc, gradually widening from macro to mid-shot to reveal the full form. Three-point studio lighting: primary key light at 45 degrees with warm 5600K color temperature, a cool fill light at 120 degrees for dimensional contrast, and a tight hair light rimming the edges with a subtle golden glow. Shallow depth of field (f/1.4) keeps the subject razor-sharp while the background melts into a creamy bokeh. Tiny light particles drift slowly through the air. Camera speed decelerates at the beauty angles, then gently accelerates between them. Final frame holds on the hero angle with the subject perfectly centered. Premium product advertisement quality, photorealistic rendering, 8K resolution, 60fps smooth motion.",

  ugc:
    "CRITICAL CONSTRAINT: The original subject must remain completely unaltered in appearance, color, and form throughout the entire video. Authentic handheld smartphone footage shot in portrait orientation (9:16). A relatable person picks up and interacts naturally with the exact subject — examining it closely, turning it in their hands, and reacting with genuine delight. Camera held at chest-to-eye level with subtle organic micro-shake and occasional gentle refocusing. Setting is a bright, minimalist apartment with soft white walls. Key light is natural window daylight (overcast, diffused) supplemented by warm ambient interior light bouncing off light surfaces. Candid energy — mid-sentence reactions, natural pauses, authentic enthusiasm. Color grading is bright, slightly lifted shadows, warm skin tones. 60fps for buttery smooth motion. Social-first vertical format optimized for TikTok, Instagram Reels, and YouTube Shorts.",

  luxury:
    "CRITICAL CONSTRAINT: Absolutely zero alterations to the product's design, proportions, materials, or branding. Ultra-premium luxury fashion house commercial. Open on a dramatic slow-motion dolly-in through swirling atmospheric haze, gradually revealing the exact subject bathed in a single shaft of warm directional light against deep black negative space. Camera movement is impossibly smooth — steady dolly transitioning to a sweeping crane arc. Chiaroscuro lighting with rich, moody shadows and selective golden-hour rim highlights that trace the subject's contours. Deep, saturated color palette: midnight blacks, burnished golds, and rich burgundy undertones. Anamorphic lens characteristics — oval bokeh, subtle horizontal flare streaks across specular highlights, natural vignetting. The atmosphere is reverent, grand, and aspirational. Pacing is deliberate and unhurried. Shot on 35mm anamorphic, 2.39:1 widescreen feel, ultra-HD 8K, cinematic film grain, photorealistic.",

  "social-media-ad":
    "CRITICAL CONSTRAINT: Keep the main subject exactly as shown in the original image — no changes to its appearance. High-impact, thumb-stopping social media advertisement designed for maximum engagement. Dynamic camera work: opens with a fast whip-pan that snaps to the subject, followed by an energetic tracking orbit with quick directional changes and dramatic push-ins on key details. Bold, contemporary lighting — mix of vibrant neon color washes (electric blue, hot pink, vivid amber) sweeping across the subject, combined with punchy high-key fill to keep details crisp. Quick-cut pacing with 2-3 distinct angle changes within the sequence. Motion graphics-friendly framing with clean negative space for text overlay zones. Colors are hyper-saturated and contrast-boosted for feed standout. Energetic, youthful, trend-forward mood. Designed to perform on Instagram, TikTok, and YouTube ads. 4K resolution, 60fps, sharp focus throughout.",

  lifestyle:
    "CRITICAL CONSTRAINT: Do not change the subject's physical appearance, colors, or design at any point. Warm, aspirational lifestyle cinematography with cinematic depth. The exact subject is placed naturally within a beautifully styled living space — think Architectural Digest meets everyday comfort. Wide-angle lens (24mm equivalent) slowly pans left-to-right, gently parallaxing foreground elements (a linen curtain edge, a ceramic vase) against the mid-ground subject and a softly blurred background of curated decor. Golden-hour sunlight streams through sheer curtains at a low angle, casting long honey-toned shadows and painting warm light across natural wood and textile surfaces. Dust motes drift lazily through the light shafts. Color grading: lifted shadows with warm amber tones, desaturated greens, and creamy highlights reminiscent of Kodak Portra 400 film stock. Gentle film grain overlay, natural lens distortion at edges. Mood is peaceful, nostalgic, and deeply inviting — the feeling of a quiet Sunday morning. 24fps for classic cinematic cadence.",

  unboxing:
    "CRITICAL CONSTRAINT: The product must look exactly as it does in the source image throughout the entire reveal. Cinematic first-person POV premium unboxing experience. Camera is positioned directly overhead (bird's eye), angled slightly forward to capture hands entering frame from bottom. Clean, manicured hands carefully lift the lid off elegant packaging, revealing tissue paper that is slowly peeled back to unveil the exact subject in a deliberate, tension-building reveal. Each movement is slow, precise, and deeply satisfying — fingertips gliding across textures, packaging materials producing subtle tactile sounds. Lighting is crisp, diffused overhead studio illumination (two large softboxes at 45-degree angles) with a subtle warm accent light from behind to create a gentle rim on the packaging edges. Background is a clean, neutral matte surface (ivory or soft grey). Macro focus racks between packaging details and the product. ASMR-inspired visual pacing — every fold, every layer matters. Minimalist, premium aesthetic. 4K resolution, 60fps for silky smooth motion, highly detailed textures.",

  custom: "",
};
